name: Greetings

on:
  push:
    branches:
    - main

jobs:
  greeting:
    runs-on: macos-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - run: echo 'hello github~!'
